spring:
  application:
    name: grm-server
  messages:
    basename: messages
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    driver-class-name: org.postgresql.Driver
    username: devuser
    password: devpass
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create-drop
  sql:
    init:
      mode: never
  h2:
    console:
      enabled: true
  
server:
  address: 0.0.0.0
  port: 8080
  forward-headers-strategy: native
